# golangci-lint設定ファイル。設定値の説明は下記参照
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

#コメントなどはデフォルトで無視されるようになっているので無効にする。
issues:
  exclude-use-default: false

# 有効にするLinters
linters:
  disable-all: true
  enable:
    - golint
    - govet
    - gofmt
    - errcheck
    - goimports

linters-settings:
  # エラーのチェック
  errcheck:
    # 型推論の使用をチェックするか 例) a:= b()
    check-type-assertions: false
    # エラーを_にして握りつぶしているのをチェックするか
    check-blank: false
    # 無視する命令
    ignore: fmt:.*,io/ioutil:^Read.*
    # 無視するファイル
    exclude: initialize/config/errcheck/exclude.txt

  # コンパイラによって検出されないエラーを見つける。書き方が悪いとか。
  govet:
    check-shadowing: true
    enable-all: true
    disable-all: false

  # コーディングのスタイルの問題を発見する。
  golint:
    #数値が低いほどチェックが厳しくなる。デフォルト0.8
    min-confidence: 0.5

  # インデントとかを整理する
  gofmt:
    # コード単純化の提案をしてくれる
    simplify: true

  # 足りないimportや使っていないimportをチェックする
  goimports:
    # 3rd-partyパッケージの後に接頭辞で始まるpackageをカンマ区切りのリストで書く
    local-prefixes: github.com/org/project