development:
    dialect: postgres
    datasource: host=postgres dbname=db user=postgres password=postgres sslmode=disable
    dir: migrations
    table: migrations

production:
    dialect: postgres
    datasource:
    dir: migrations
    table: migrations