version: '3'

services:
  postgres:
    container_name: postgres
    ports:
      - 5432:5432
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db

  api:
    container_name: api
    ports:
      - 8000:8000
      - 5002:5002
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    environment:
      - GOPATH=/go
    volumes:
      # ホストOS：コンテナ側
      - ./go:/go/src/github.com/birnamwood/go-nuxt/
    command: realize start --server