// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/birnamwood/go-nuxt/pkg/infrastructure/persistence"
	"github.com/birnamwood/go-nuxt/pkg/interface/handler"
	"github.com/birnamwood/go-nuxt/pkg/usecase"
	"gorm.io/gorm"
)

// Injectors from di.go:

func InitializeUserHandler(db *gorm.DB) handler.UserHandler {
	userRepository := persistence.NewUserPersistence(db)
	userUsecase := usecase.NewUserUsecase(userRepository)
	userHandler := handler.NewUserHandler(userUsecase)
	return userHandler
}
