server:
  port: 8000

api:
  version: v1

db:
  # Dockerを使う場合はアドレスではなくコンテナ名を指定する
  host: postgres
  port: 5432
  dbname: db
  user: postgres
  password: postgres

log:
  filename: log/app.log
  maxsize: 50 # /MB :ローテーションされる前のメガバイト単位の最大サイズ。超えるとfile名-日付.拡張子で保存される
  maxbuckups: 10 # /days :保持する古いログファイルの最大数です。
  maxage: 30 # /days :古いログファイルを保持する最大日数
