settings:
  legacy:
    # コンテナの場合レガシーモードでないと動かない
    force: true
    interval: 0s
server:
  status: true
  open: false
  # ホストはコンテナ名で指定
  host: api
  port: 5002
schema:
- name: go-nuxt
  path: .
  commands:
    install:
      status: true
      method: go build -o go-nuxt
    run:
      status: true
      method: ./go-nuxt
  watcher:
    extensions:
    - go
    - yaml
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
