server:
  port: 8000

api:
  version: v1

db:
  # Dockerを使う場合はアドレスではなくコンテナ名を指定する
  host: postgres
  port: 5432
  dbname: db
  user: postgres
  password: postgres

log:
  filename: log/app.log
  filename2: log/http.log
  maxsize: 10 # /MB :ローテーションされる前のメガバイト単位の最大サイズ。超えるとfile名-日付.拡張子で保存される
  maxbuckups: 3 # /days :保持する古いログファイルの最大数です。
  maxage: 5 # /days :古いログファイルを保持する最大日数

firebase:
  credential: initialize/config/firebase/golang-messaging-firebase-adminsdk-15hkq-c1c52b1a01.json