name: Check Go Project
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - 1.15
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - name: checkout
      uses: actions/checkout@v2

    - name: Install golang-ci lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.32.2
        sudo mv ./bin/golangci-lint $GOPATH/bin/

    - name: Run golangci-lint
      run: golangci-lint run

    - name: go get
      run: go get -v -t -d ./...
      
    - name: go test
      run: go test -v ./...