name: Check Go Project
on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.15.x]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: checkout
      uses: actions/checkout@v2

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: golang-ci lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.32

    - name: Run golangci-lint
      run: golangci-lint run

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: go test
      run: go test -v ./...